apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
   run.googleapis.com/ingress: internal-and-cloud-load-balancing
  name: deploy-springcloudrun-dev
spec:
  template:
    spec:
      containers:
      - image: my-app-image