apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: springcloudrun
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-service-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - run-service-prod.yaml
deploy:
  cloudrun: {}  